version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=yoursecretkey
      - DEBUG=1 # For development. Set to 0 in production.
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  db:
    image: postgres
    environment:
      - POSTGRES_DB=yourdbname
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
