# Generated by Django 5.0 on 2024-01-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='description',
            new_name='name',
        ),
    ]
